name: uni_ride
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.0

# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  figma_squircle: ^0.6.3
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.1
  go_router: ^16.2.1
  persistent_header_adaptive: ^2.1.3
  sliver_tools: ^0.2.12
  timeline_tile: ^2.0.0

dev_dependencies:
  flutter_lints: ^5.0.0
